### PR TITLE
Use BaseVariant.getJavaCompileProvider() where available

### PR DESCRIPTION
**Pull request by dmazzoni**
This ensures compatibility of the ```sonarqube``` task with Gradle 5.

Updated the Gradle plugin to version ```3.3.0``` and the Gradle wrapper to version ```4.10.1```.

### CODE REVIEW

**Comment by henryju** [comment]
Is the task completely broken with Gradle 5? Or only when analyzing an Android project?

**Comment by dmazzoni** [comment]
It seems to be an Android-only issue. I have just integrated the SonarQube plugin (version ```2.7```) into Spring's sample Gradle project (https://github.com/spring-guides/gs-gradle), updated it to Gradle ```5.2.1```, and had no issues.

**Comment by henryju** [comment]
Thanks, I have updated ticket https://jira.sonarsource.com/browse/SONARGRADL-56 accordingly. We will review/test/merge your PR during next sprint on the scanner for Gradle.

**Comment by SylvainGourdaut** [comment]
Hi, any update on this ?

**Comment by pierre-guillot-sonarsource** [comment]
As this request have been taken into account into the sonarsource product backlog, i'm closing this. You can use the `watch` feature of our jira to get notified of further progress.

**Pull request closed without merging**
