### PR TITLE
Allow customizing SonarQubeTask logger levels

### PR DESCRIPTION
**Pull request by mikejhill**
> Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
> 
> With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
> 
> - [x] Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make

`INFO`-level logging is often required in order to get meaningful SonarScanner output. For example, a number of detected configuration elements as well as the scan progress are only sufficiently included at the `INFO` level.

The SonarScanner Gradle plugin passes log statements directly to Gradle at their original severity, but Gradle only allows configuring the logger level globally, meaning that the `INFO` level must be configured for _all_ Gradle tasks in order to get the desired SonarScanner output. This leads to very large logged volumes, particularly for large projects. This has a detrimental impact on our CI and Gradle Enterprise environments, while also making output more difficult to interpret.

This PR allows configuring the logger level for SonarScanner specifically, such that logs at the specified severity or higher are always passed to Gradle at the `LIFECYCLE` level. Example usage:
```kotlin
project.tasks.named<SonarQubeTask>("sonarqube") { useLoggerLevel(LogLevel.INFO) }
```

We have recently implemented this patch in our organization and are currently using it with success.

> - [x] Use the following formatting style: [SonarSource/sonar-developer-toolset](https://github.com/SonarSource/sonar-developer-toolset#code-style)
> - [ ] Provide a unit test for any code you changed

The unit test suite doesn't seem to be enabled (looks like I need to add `useJUnitPlatform()` to the `test` task for it to run, but immediately run into some failures). However, the integrations tests are.

Can you advise on the preferred direction for testing? Should we add another sample project in the integration test resources for this?

> - [x] If there is a [JIRA](http://jira.sonarsource.com/browse/SONARGRADL) ticket available, please make your commits and pull request start with the ticket ID (SONARGRADL-XXXX)
>   N/A
> 
> We will try to give you feedback on your contribution as quickly as possible.
> 
> Thank You!
> The SonarSource Team
>

### CODE REVIEW

**Comment by lukasz-jarocki-sonarsource** [comment]
Hi @dbmeneses , do you think this is something needed? Could you take a look?

**Comment by dbmeneses** [comment]
@mikejhill thanks, it looks good - I'll try to fix the unit test execution and then I'll ask you to add unit tests for this feature.

**Comment by jacek-poreda-sonarsource** [comment]
Tests have been fixed, so I think it should be good to go, I will let you confirm this @dbmeneses

**Comment by wouter-admiraal-sonarsource** [comment]
Hi @mikejhill. Any news on your side? Can we help you with the unit tests?

**Comment by mikejhill** [comment]
Sorry, I have this on my queue but haven't had time to get back to this yet. If somebody else is able to contribute unit tests that would be great, otherwise I will try to get back to this within the next couple of weeks.

**Comment by dbmeneses** [comment]
Thanks for the contribution.
I've added unit and integration tests to your commit and opened #120 
 ticket created for it: https://sonarsource.atlassian.net/browse/SONARGRADL-94

**Pull request closed without merging**
