### PR TITLE
Skip transient failures

### PR DESCRIPTION
**Pull request by Sineaggi**
If sonarqube is down (or is otherwise throwing transient errors), we might want to allow failures to not fail the whole gradle task.
In our case, sonarqube went down for a bit and we saw failures on users.
```
<snip>
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)	
Caused by: org.sonarsource.scanner.api.internal.ScannerException: Unable to execute SonarScanner analysis	
at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:85)	
•••
at org.sonarqube.gradle.SonarQubeTask.run(SonarQubeTask.java:101)	
•••
Caused by: java.lang.IllegalStateException: Fail to get bootstrap index from server	
at org.sonarsource.scanner.api.internal.BootstrapIndexDownloader.getIndex(BootstrapIndexDownloader.java:42)	
•••
at org.sonarqube.gradle.SonarQubeTask.run(SonarQubeTask.java:101)	
•••
Caused by: java.lang.IllegalStateException: Status returned by url [our_sonarqube_url] is not valid: [502]
at org.sonarsource.scanner.api.internal.ServerConnection.callUrl(ServerConnection.java:118)	
at org.sonarsource.scanner.api.internal.ServerConnection.downloadString(ServerConnection.java:99)	
at org.sonarsource.scanner.api.internal.BootstrapIndexDownloader.getIndex(BootstrapIndexDownloader.java:39)	
at org.sonarsource.scanner.api.internal.JarDownloader.getScannerEngineFiles(JarDownloader.java:58)	
at org.sonarsource.scanner.api.internal.JarDownloader.download(JarDownloader.java:53)	
at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:76)	
at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:74)	
at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:70)	
at org.sonarsource.scanner.api.EmbeddedScanner.doStart(EmbeddedScanner.java:185)	
at org.sonarsource.scanner.api.EmbeddedScanner.start(EmbeddedScanner.java:123)	
at org.sonarqube.gradle.SonarQubeTask.run(SonarQubeTask.java:101)	
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)	
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)	
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)	
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)	
at org.gradle.api.internal.tasks.execution.TaskExecution$2.run(TaskExecution.java:239)	
<snip>
```
It seems reasonable to want to allow for transient sonarqube errors to not fail the whole task.

### CODE REVIEW

**Comment by Sineaggi** [comment]
Alternatively, if the `org.sonarsource.scanner.api.internal.ScannerException` could contain a subclass or sibling `TransientScannerException` that was only thrown for 5xx and related errors, then we could catch that. That way client configuration errors could still fail the task.

**Comment by dbmeneses** [comment]
@Sineaggi to be honest this looks like a very particular need.
Also, even if the task fails, can't you accomplish what you need by ignoring the  gradle's failure? Even if other tasks are running, maybe `--continue` could be used?

**Comment by Sineaggi** [comment]
Unfortunately `--continue` still fails the whole build, which would prevent our ci pipeline from continuing.

**Comment by dbmeneses** [comment]
Gradle is expected to fail with `--continue`, but execute other tasks if possible.
I believe the PR is about a very specific need and the strategy is not generally accepted as best practice. There's no guarantee that the failure is actually transient, and also the failure could happen in any other WS call. In general failures shouldn't be ignored, even if transient. 
Lastly, there are many other potential solutions around transient problems: check for a connection before starting the task (with another task), gracefully handle gradle failing on the CI/CD script, extend the sonarqube ask, etc.

**Pull request closed without merging**
